[project]
name = "a2a-basics"
version = "0.1.0"
description = "AutoGen agent-to-agent basics"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "autogen>=0.9.9",
  "python-dotenv>=1.0",
]

[tool.uv]
package = false
