[project]
name = "fastmcp-tool-demo"
version = "0.1.0"
description = "Minimal FastMCP tool and client example"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "fastmcp>=2.12,<3.0",
]

[tool.uv]
package = false
